=== zxstephenson/tcloud/cloud-modules/cloud-context/src/main/java/com/cloud/context/xml/api.xsd
<?xml version="1.0"?>  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  
           targetNamespace="http://www.w3.org/2001/XMLSchema"  
           xmlns="http://www.w3.org/2001/XMLSchema"  
           elementFormDefault="qualified">  
  
    <xs:element name="note">  
        <xs:complexType>  
            <xs:sequence>
                <xs:element name="to" type="xs:string"/>  
                <xs:element name="from" type="xs:string"/>  
                <xs:element name="heading" type="xs:string"/>  
                <xs:element name="body" type="xs:string"/> 
                <xs:element name="age" type="xs:int"></xs:element>
				<xs:element name="interface"> 
		<xs:complexType> 
			<xs:sequence> 
				<xs:element name="publicparams" maxOccurs="unbounded"> 
					<xs:complexType> 
						<xs:sequence> 
							<xs:element name="param" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType> 
									<xs:attribute name="key" type="xs:string" /> 
									<xs:attribute name="value" type="xs:string" /> 
								</xs:complexType> 
							</xs:element> 
						</xs:sequence> 
						<xs:attribute name="code" type="xs:string" default="default"/> 
					</xs:complexType> 
				</xs:element> 
			</xs:sequence> 
		</xs:complexType> 
	</xs:element>
            </xs:sequence>  
        </xs:complexType>  
    </xs:element>
  
  	
  
</xs:schema>

=== zxstephenson/tcloud/cloud-webapp/demo-service01/src/main/resources/schame/api.xml
<?xml version="1.0"?>  
<note xmlns="http://com.cloud.api"  
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
      xsi:schemaLocation="classpath:/META-INF/api.xsd">

  <to></to>
  <from></from>
  <heading></heading>
  <body></body>
<age></age>
  <interface>
  	<publicparams code="default">
  		<param />
  	</publicparams>
  </interface>
    
</note>
